name: Python application test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Ensure to use the latest version
    - name: Set up Python 3.11.7
      uses: actions/setup-python@v3 # Ensure to use the latest version
      with:
        python-version: '3.11.7' # Updated to Python 3.11.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run tests
      run: |
        pytest
